---
Name: jellygnite-elementalstyle
After: jellygnite-elements
---
DNADesign\Elemental\Models\BaseElement:
  inline_editable: false
  extensions:
    - Jellygnite\ElementalStyle\Extensions\DynamicStyleExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - sunnysideup/silverstripe-elemental-style:client/dist/javascript/bundle.js
  extra_requirements_css:
    - sunnysideup/silverstripe-elemental-style:client/dist/css/bundle.css
PageController:
  extensions:
    - Jellygnite\ElementalStyle\Extensions\PageControllerExtension
